services:
  app:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: pym_node
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - pym
    environment:
      - TZ=America/La_Paz
      - PORT=5000
      - URI=0.0.0.0
      - NODE_ENV=production
    volumes:
      - ./backend-pym/app/public:/app/app/public
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: pym_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro  # Montar certificados SSL
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - app
    networks:
      - pym
    environment:
      - TZ=America/La_Paz

  postgres:
    image: postgres:15.5
    container_name: pym_db
    restart: always
    environment:
      - POSTGRES_USER=pym_user
      - POSTGRES_DB=db_pymsystems
      - POSTGRES_PASSWORD=fzZf9DdAZi
      - TZ=America/La_Paz
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - pym

volumes:
  postgres_data:

networks:
  pym:
    driver: bridge