version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: pym_node
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - pym
    environment:
      - TZ=America/La_Paz
    volumes:
      - ./backend-pym/src/app/public:/app/src/app/public
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: pym_web
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/frontend.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - app
      - postgres
    networks:
      - pym
    environment:
      - TZ=America/La_Paz
  postgres:
    image: postgres:18.1
    container_name: pym_db
    restart: always
    environment:
      - POSTGRES_USER=pym_user
      - POSTGRES_DB=db_pymsystems
      - POSTGRES_PASSWORD=fzZf9DdAZi
      - TZ=America/La_Paz
    ports:
      - 5555:5432
    volumes:
      - ./schemas:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - pym

volumes:
  pym: 
  nginx:

networks:
  pym:
    driver: bridge

