server {
    listen 88;
    listen [::]:88;
    server_name test.sinna.justicia.gob.bo;
    root /usr/share/nginx/html;
    
    index index.html index.htm index.nginx-debian.html;
        
    location / {
      try_files $uri $uri/ @rewrites @backend;
  	}

  	location @rewrites {
    		rewrite ^(.+)$ /index.html last;
  	}

    access_log /var/log/nginx/rmrv-access.log;
    error_log /var/log/nginx/rmrv-error.log;

    location @backend {
        proxy_pass http://app:5000; # Cambia esto según el puerto en que corre tu aplicación
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
